os:
  - linux

language: cpp

before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get update

install:
  - sudo apt-get install libarmadillo4 libarmadillo-dev
  - sudo apt-get install cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j6
  - ./run_experiment.py
